---
title: "Entrega articulo: Statistical description for survival data"
author: "Miguel Diaz"
date: '2022-07-03'
output: html_document
---
##**Asumir los datos como un cultivo de palma**
Tiempo = time: Variable respuesta: Tiempo de supervivencia
Edad = Age: meses de plantación
Hibrido = Sex: hibrido 1, hibrido 2
Severidad = ph.ecog: severidad en la misma escala
Estado = status
N17 = meal.cal: Nitrogeno medido en la hoja 17
P17 = wt.loss: Fosforo medido en la hoja 17

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Primero se debe cargar la libreria y el dataframe prehecho para el analisis
library(survival)
str(lung)
max(lung$time)
min(lung$time)
max(lung$age)
min(lung$age)
```

```{r}
#Con los maximos y minimos del tiempo y la edad, se decide hacer unos ajustes para que sea un escenario mas parecido a palma, se plantea manejar todo en meses
#Simplemente se cambia el nombre de las variables en este chunk
Tiempo<- (lung$time)/8
Edad<- (lung$age)/1.014306760
Hibrido<- lung$sex
Estado <- lung$status
Severidad <- lung$ph.ecog
N17 <- lung$meal.cal
P17<- lung$wt.loss
DataPalma<-data.frame(Tiempo, Edad, Hibrido, Estado, Severidad, N17, P17) #Se crea el nuevo datafarme
```


```{r}
SurvPalma<-Surv(Tiempo, Estado)
# lung.sur
class(SurvPalma)
```

```{r}
Palma.fit<-survfit(SurvPalma~1)
summary(Palma.fit)
#Aqui se puede ver la supervivencia con respecto al tiempo
```
```{r}
plot(Palma.fit,xlab="Meses",ylab="Proporción de palmas")
abline(h = 0.5, col='red') #Donde estan la proporcion del 50% de las palmas segun la matriz de arriba
abline(v = 38.25, col='red') #Tiempo donde muere el 50% de las palmas segun la matriz de arriba
abline(h = c(0.25, 0.75), col='blue')
abline(v = c(20.8, 68.7), col='blue') #Tiempo donde muere el 25% y el 75% de las palmas segun la matriz de arriba
```
```{r}
#Aqui basicamente se busca representar graficamente un intervalo para la supervivencia y no solo un punto especifico
plot(Palma.fit,xlab="Meses",ylab="Proporción de palmas")
abline(h = 0.5, col='red')
abline(v = 38.25, col='red')
points(c(38.25, 38.25), c(0.43, 0.57), pch =16, col='blue')
points(c(34.25, 42.25), c(0.5, 0.5), pch =16, col='red')
```

```{r}
Palma.fit.strata<-survfit(SurvPalma~Severidad,DataPalma)
plot(Palma.fit.strata, lty = 1:4,col=1:4,xlab="Meses",ylab="Proporcion de palmas",
     lwd=3)
legend(88, .9, c("Severidad=0", "Severidad=1","Severidad=2","Severidad=3"), lty = 1:4,col=1:4, lwd=3)
abline(h = 0.5)
```

```{r}
Palma.fit.strata<-survfit(SurvPalma~Hibrido,DataPalma)

plot(Palma.fit.strata, conf.int = 0.95,
     col=1:2, xlab = 'Meses', lwd=1)
legend(88, .9, c("Hibrido 2", "Hibrido 1"), col=1:2, lwd=3)
abline(h = 0.25, col = 'blue', lwd=2)
abline(h = 0.5, col = 'blue')
abline(v = c(26.25, 40), col = 1)
abline(v = c(43.75, 68.75), col = 2)
#El tiempo de supervivencia es menor para las palmas del hibrido 2 con respecto a las palmas del hibrido 1
```



```{r}
## Intervalos de Confianza para el estimador Kaplan-Meier
library(km.ci)
a<-km.ci(Palma.fit, conf.level=0.95, tl=NA, tu=NA, method="loghall")
plot(a, lty=2, lwd=2, col = 'red',xlab='Meses',ylab="Proporcion de palmas",)
lines(Palma.fit, lwd=2, lty=1, col = 'black')
lines(Palma.fit, lwd=1, lty=4, conf.int=T, col = 'blue')
linetype<-c(1, 2, 4)
legend(74, .9, c("Kaplan-Meier", "Hall-Wellner", "Pointwise"),
       lty = linetype,
       col = c('red', 'black', 'blue'))

abline(h = 0.5, col='maroon3', lwd=2)
abline(v = 38.75, col='maroon3', lwd=2)

```

```{r}
aalen.fit<- survfit(coxph(SurvPalma~1), type="aalen")
sum_aalen.fit = summary(aalen.fit)

plot(aalen.fit,xlab='Meses',ylab="Proporcion de palmas", col="red",lwd=1,lty=1)
lines(Palma.fit, lwd=1, lty=1)
legend(25, .9,
       c("Nelson-Aalen", "Kaplan-Meier"),
       lty=c(1,1),
       col=c("red", "black"))
#No parametricos, los estimadores son similares
```

```{r}
barplot(sum_aalen.fit$time, cumsum(sum_aalen.fit$n.event),xlab='Palmas muertas en el tiempo')
```

```{r}
mod_suv = lm(cumsum(sum_aalen.fit$n.event) ~ sum_aalen.fit$time)
summary(mod_suv)

plot(sum_aalen.fit$time, cumsum(sum_aalen.fit$n.event),xlab='Meses',ylab="Palmas muertas", pch = 16)
abline(mod_suv)
```

```{r}
survdiff(SurvPalma~Severidad,DataPalma)

# Prueba de log-rank or Mantel-Haenszel
survdiff(SurvPalma~Hibrido,DataPalma, rho = 0)
# Preuba de Peto & Peto modification of the Gehan-Wilcoxon test
survdiff(SurvPalma~Hibrido,DataPalma, rho = 1)


survdiff(SurvPalma~Hibrido + Severidad,DataPalma)
```


### Modelo Parametrico

```{r}
par.wei<-survreg(SurvPalma~1,dist="w")
par.wei
```

```{r}
kappa<-par.wei$scale
lambda<-exp(-par.wei$coeff[1])
zeit<-seq(from=0,to=130,length.out=130)
s<-exp(-(lambda*zeit)^kappa)
h<-lambda^kappa *kappa*zeit^(kappa-1)
par(mfrow=c(2,1))
plot(zeit,h,xlab="Meses",ylab="h(t)", pch = 16, cex = 0.1, las = 1)
plot(zeit,s,xlab="Meses",ylab="s(t)", pch = 16, cex = 0.1, las = 1)
#Graficos de riesgo y supervivencia
```

